export const stockData = [
  {
    id: 1,
    productName: "Dell Laptop",
    description: "TWTR",
    cost: "22.76 USD",
    stockCount: 10,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
  {
    id: 2,
    productName: " Samsung Washing Machine",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 4,
    image: "https://dummyimage.com/450x400/dee2e6/6c757d.jpg",
  },
  {
    id: 3,
    productName: "Asus ZenBook  ",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 3,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
  {
    id: 4,
    productName: "Apple MacBook Air(2020)",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 2,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
  {
    id: 5,
    productName: "MITSUBISHI Air Conditioner Invertor",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 6,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
  {
    id: 6,
    productName: "Vivo V17 Pro",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 4,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
  {
    id: 7,
    productName: "Westinghouse Blender 1.5L",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 5,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
  {
    id: 8,
    productName: "Acer Laptop",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 4,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
  {
    id: 9,
    productName: "HP Laptop",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 8,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
  {
    id: 10,
    productName: "LG Smart Inverter Refrigerator",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 10,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
  {
    id: 11,
    productName: "iPhone 13 Mini -256GB",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 4,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
  {
    id: 12,
    productName: "iPhone 13 Pro Max-256GB",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 2,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
  {
    id: 13,
    productName: "SAMSUNG GALAXY M32",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 5,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
  {
    id: 14,
    productName: "Washing Machine",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 4,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
  {
    id: 15,
    productName: "SAMSUNG HD LED Tv 32",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 4,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
  {
    id: 16,
    productName: "Abans Mini Hifi System",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 7,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
  {
    id: 17,
    productName: "Washing Machine",
    description: "This product is nice ",
    cost: "17.76 USD",
    stockCount: 4,
    image: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
  },
];
export default stockData;
